### ISSUE TITLE
Don't include catkin folder structure

### ISSUE THREAD

**Issue by Achllle** [PUT-UGV-Team/leo-marsyard#2]
Instead of asking users to remove `/devel` and `/build`, simply include the contents of `/src` in this repo and instruct people to `mkdir -p leo_ws/src`. That way you also support multiple packages of different source in the same workspace without git conflicting.

**Comment by filesmuggler** [comment]
Thank you for the feedback. We changed the structure of the repo so it can be used as separate set of packages.
